Upload, upload tests, fix rate with git install in docker containers, rate tests
ECE-461-Project/ECE461_Project_Part2 pull request #74
Opened 2023-04-11 01:07 UTC by priyankapereira1

Completed package upload with tests.

Upload has 2 options, ingestible public URL input, or base64 encoded zip input.
Stores packages that are inputted and/or git cloned in /tmp/npm-package-**** just like how it was for your Part 1 for simpler integration.

This WILL BE CHANGED! Simple fix on next iteration.

Tests in tests/integration_tests/package_upload_and_rate.test.ts do not seed the database, but run upload on various inputs to populate the database, then for one successful rating check on one of the uploaded packages (need a valid cloned/stored location for rating endpoint to work).

Tests in tests/integration_tests/package_rate.test.ts only do invalid checks on the rating endpoint.

2023-04-11 01:24 UTC, priyankapereira1 commented
Will fix the FK_UserID fields when creating a database entry on upload next, on a new branch. Feel free to look over and merge if ready.

2023-04-14 02:39 UTC, just007in requested changes

2023-04-14 02:39 UTC, just007in commented on src/api_server/zip_files.ts
Please use writeFile from 'fs/promises' package. Line 67

2023-04-14 02:39 UTC, just007in commented on src/api_server/get_files.ts
Please use readFile from 'fs/promises'

2023-04-14 02:39 UTC, just007in commented on src/api_server/db_connector.ts
Is there a reason to change packageid to be non unique string?

2023-04-14 02:39 UTC, just007in commented on docker/API/Dockerfile
We should instead use isomorphic git package if possible

2023-04-14 16:10 UTC, priyankapereira1 commented on src/api_server/db_connector.ts
example response had a lowercase string as PackageID
models also has PackageID as string

2023-04-14 16:10 UTC, priyankapereira1 commented on src/api_server/get_files.ts
can do, but what is the rationale?

2023-04-14 16:13 UTC, priyankapereira1 commented on src/api_server/zip_files.ts
rationale?

2023-04-14 16:13 UTC, priyankapereira1 commented on docker/API/Dockerfile
this should work, is there a reason it would not?

2023-04-14 17:19 UTC, just007in commented on src/api_server/zip_files.ts
Synchronous functions blocks the whole main thread so using the async function instead is better

2023-04-14 17:19 UTC, just007in commented on src/api_server/get_files.ts
Synchronous functions blocks the whole main thread so using the async function instead is better

2023-04-14 17:20 UTC, just007in commented on src/api_server/db_connector.ts
Ah OK didn't realize that

2023-04-14 17:23 UTC, just007in commented on docker/API/Dockerfile
Yeah this should work. I thought we were going to use isomorphic git

2023-04-15 00:39 UTC, priyankapereira1 commented on src/api_server/zip_files.ts
on it! newest commit should fix this

2023-04-15 00:39 UTC, priyankapereira1 commented on src/api_server/get_files.ts
on it, newest commit should fix this :)

2023-04-15 00:41 UTC, priyankapereira1 commented
> Will fix the FK_UserID fields when creating a database entry on upload next, on a new branch. Feel free to look over and merge if ready.

fixed on newest commit

2023-04-15 16:22 UTC, just007in approved these changes

2023-04-16 18:38 UTC, merged